### ISSUE TITLE
How to load method & classes from gems?

### ISSUE THREAD

**Issue by khrisnagunanasurya** [ruby/rbs#1066]
Hi, I just started using RBS and want to implement it to rails, and I'm using the AASM gem on the model, but somehow RBS can't load it, and I'm not sure how to add the method and class dependencies on the RBS file only.
And this is what I've been trying so far.

```
# sig/app/models/{model_name}/sub_model.rbs
class ModelName
  class SubModel < ::ModelName
    STATUS_ALIASES: Hash[Symbol, String]
    STATUS_STAGES: Hash[Symbol, String]
    INITIAL_STATUSES: Array[Symbol]

    module GeneratedAttributeMethods
      def id: () -> Integer
      def id=: (Integer) -> Integer
      ...
    end
    include GeneratedAttributeMethods

    module AasmGem
      def event: (Symbol) -> void

      def transitions: (from: Symbol, to: Symbol) -> void
    end
    include AasmGem
  end
end
```

The error I getting
<img width="880" alt="image" src="https://user-images.githubusercontent.com/6211333/179666499-807c8ffa-459d-4b1c-89ed-fef6df20c42d.png">

Does someone have this problem in the past and can help me to fix it? thanks

**Comment by ksss** [comment]
It's a case where instance_exec changes the `self` in block.
There is no established way to solve this case so far.
It can be partially handled by using the annotation of steep, but it will be necessary to insert a comment each time.

```rb
aasm({ column: :status_after }) do
  # @implements AASM::Base
  event :to_deactivated do
    # @implements AASM::DslHelper::Proxy
    transitions from: %i[active active_upgrade], to: :deactivated
  end
end
```

**Comment by khrisnagunanasurya** [comment]
The answer is related to https://github.com/pocke/rbs_rails/issues/230
