### ISSUE TITLE
How to deal with mutable defined method name in eval

### ISSUE THREAD

**Issue by m11o** [ruby/rbs#1116]
I don't know how to write types for a method defined by a mutable method name.
The method name is named by configures file etc.

For example

```ruby
mutable_defined_name = 'foo'

eval <<-METHOD
  Class Hoge
    def #{mutable_defined_name}(args)
      # do something
    end
  end
METHOD
```

sample
https://github.com/kaminari/kaminari/blob/bf20fccfdbf7d10c337aeead7ecf4f54a230a5fb/kaminari-activerecord/lib/kaminari/activerecord/active_record_model_extension.rb#L14-L22

Would you please tell me how to deal with them if there are how to write rbs?

**Comment by soutaro** [comment]
Currently, I recommend writing the *name*s explicitly. 

```rbs
class Model < ApplicationRecord
  def self.page: (?Integer?) -> ActiveRecord_Relation
end
```

It will tell the exact method names clearly. This would work good for the case of Kaminari because it's not that dynamic.

More dynamic cases will be supported with custom generators -- like [RBS Rails](https://github.com/pocke/rbs_rails) or [Orthoses](https://github.com/ksss/orthoses) middlewares.

**Comment by m11o** [comment]
Thank you for your advice!

**Comment by ksss** [comment]
RBS is static, so the method name must be determined.
gem_rbs_collection can only store static files. (Default settings may be added).
I think the only way to determine the method name more accurately is to generate the RBS on the application side.

```mermaid
graph TD
    subgraph gem_rbs_collection
    A[kaminari]
    end

    subgraph user
    A[library RBS] --> |load| B[Final RBS set]
    C[Application] --> |load| D[Generator]
    D --> |generate| B
    B --> |use| E[Editor]
    end
```

**Comment by m11o** [comment]
Thanks!
I understood the `self.page` method might be a good idea to add gem_rbs_collection because the method name is often used in many cases. And, as you said, it needs to be defined rbs on the application if it is set to the other name.
