### ISSUE TITLE
`rbs prototype rb` misunderstand `include` in `class << self `

### ISSUE THREAD

**Issue by liggest** [ruby/rbs#1196]
```Ruby
#test.rb
module A
  def foo = p :foo
end

class B
  class << self
    include A
  end
end
```
```shell
$ rbs -v
rbs 2.8.2

$ rbs prototype rb test.rb

module A
  def foo: () -> untyped
end

class B
  include A
end
```

Maybe `include` declared in `class << self` should be `extend` in rbs's class declaration?
Or it would be nice if rbs could share the same syntax form of `class << self` with ruby
> Please correct me if I miss something

**Comment by pocke** [comment]
`include` in `class << self` and `extend` are exactly the same except the hooks. `include` calls `Module#included` but `extend` calls `Module#extended`. It means they are the same on the inheritance tree.


Therefore I agree with your first idea, which is converting `include` in `class << self` to `extend`.
