### ISSUE TITLE
How to write type signatures for argument with default value?

### ISSUE THREAD

**Issue by kouwasi** [ruby/rbs#1206]
Just example, I'm trying to write type signature for below class.

```rb
class Test
  def initialize(argument = 'value')
    p argument
  end
end
```

The type signature is this.

```rbs
class Test
  def initialize: (String) -> void
end
```

The first argument is clearly String. Also default value is the same.
However steep displays an error.

```
[error] The method parameter has different kind from the declaration `(::String) -> void`
│ Diagnostic ID: Ruby::DifferentMethodParameterKind
│
└     def initialize(argument = 'value')
```

I written wrong syntax? RBS(or Steep?) doesn't support default value of arguments?

**Comment by ksss** [comment]
It can be expressed by an optional parameter.

https://github.com/ruby/rbs/blob/master/docs/syntax.md#parameters

The type name can be prefixed with `?` to make it an optional parameter.

```
class Test
  def initialize: (?String) -> void
end
```

**Comment by kouwasi** [comment]
That makes sense! Literally that's an optional.

Thank you.
