### ISSUE TITLE
The return type of a method is determined incorrectly if a ternary operator is present

### ISSUE THREAD

**Issue by afuno** [ruby/rbs#1322]
This code will be accepted as correct:

```ruby
def prepared_types
  @types.map do |type|
    if type.is_a?(String)
      Object.const_get(type)
    else
      type
    end
  end
end
```

But this code will get an error in RubyMine:

```ruby
def prepared_types
  @types.map do |type|
    type.is_a?(String) ? Object.const_get(type) : type
  end
end
```

Error text:

> Incompatible types
> Required: Array<Class>
> Returned: Array<Class | String>

RBS:

```rbs
def prepared_types: -> Array[Class]
```

---

rbs (3.1.0)
RubyMine 2023.1.1

**Comment by afuno** [comment]
Here's another example that seems to be related to the condition too:

```ruby
def add_error(message, **arguments)
  message = message.call(**arguments) if message.is_a?(Proc)

  errors.push(message)
end
```

RBS:

```rbs
def add_error: (String | Proc message, **untyped arguments) -> Array[String]
```

The `message` inside the `push` method has this error:

> Incompatible types
> Required: String
> Passed: String | Proc

**Comment by hjwylde** [comment]
Hi @afuno, thank you for the report. Soutaro is right and this issue is specific to RubyMine, so you can raise a ticket here: https://youtrack.jetbrains.com/newIssue?project=RUBY - this will get assigned to us and we can look into getting it fixed :)
