### ISSUE TITLE
ruby versions support

### ISSUE THREAD

**Issue by Shibbaz** [ruby/rbs#1362]
Hello. It looks good damn amazing. Does it support ruby 3.2.2?

**Comment by pocke** [comment]
> Does it support ruby 3.2.2?

Yes, RBS supports Ruby 3.2.2. It tested on the latest Ruby.

https://github.com/ruby/rbs/blob/3c7387eb43c70f2f3f1d0158c9f0993ab387500f/.github/workflows/ruby.yml#L17C26-L17C26

If you have any trouble with Ruby 3.2, feel free to open an issue. Thanks.

**Comment by Shibbaz** [comment]
@pocke Unfortunately There is error with namespaces.

My Concepts::Users::Repository is not found by RBS, alternatively I've used sorbet.

**Comment by pocke** [comment]
I guess you do not define `Concepts::Users::Repository` class in RBS.
RBS is not aware of classes/modules in Ruby code. Therefore you need to define classes in RBS even if you have a class definition in Ruby.

You can write the class by hand or generate by a tool such as `rbs prototype`.
