### ISSUE TITLE
Many Kernel methods are defined as Object methods

### ISSUE THREAD

**Issue by ksss** [ruby/rbs#1475]
I think these should be `Kernel` methods, not `Object`.

```rb
require 'rbs'

env = RBS::Environment.from_loader(RBS::EnvironmentLoader.new).resolve_type_names
defined_kernel_methods = env.class_decls[TypeName("::Kernel")].primary.decl.members.grep(RBS::AST::Members::MethodDefinition).map(&:name)
defined_object_methods = env.class_decls[TypeName("::Object")].primary.decl.members.grep(RBS::AST::Members::MethodDefinition).map(&:name)
((Kernel.instance_methods.sort - defined_kernel_methods) & defined_object_methods).each do |sym|
  puts "- [ ] #{sym}"
end
```

- [ ] !~
- [ ] <=>
- [ ] ===
- [x] class
    - already defined
- [ ] clone
- [ ] define_singleton_method
- [ ] display
- [ ] dup
- [ ] enum_for
- [ ] eql?
- [ ] extend
- [ ] freeze
- [ ] frozen?
- [ ] hash
- [ ] inspect
- [ ] instance_of?
- [ ] instance_variable_defined?
- [ ] instance_variable_get
- [ ] instance_variable_set
- [ ] instance_variables
- [ ] is_a?
- [ ] itself
- [ ] method
- [ ] methods
- [ ] nil?
- [ ] object_id
- [ ] private_methods
- [ ] protected_methods
- [ ] public_method
- [ ] public_methods
- [ ] public_send
- [ ] remove_instance_variable
- [ ] respond_to?
- [ ] send
- [ ] singleton_class
- [ ] singleton_method
- [ ] singleton_methods
- [ ] tap
- [ ] to_s
- [ ] yield_self

**Comment by ParadoxV5** [comment]
That’s a Ruby implementation problem ¯\\\_(ツ)_/¯
```ruby
Object.instance_methods(false) #=> []
```
Everything is actually all defined in Kernel, with Object merely BasicObject + Kernel.
The API docs put instance methods (as opposed to utility functions like `print`) on the Object page for our convenience (façade). The RBSs just followed suit.

**Comment by ksss** [comment]
I found this PR. https://github.com/ruby/rbs/pull/86

@soutaro 
Do you still think the same way?
I am concerned about the meaning of RBS as a document.

**Comment by soutaro** [comment]
+1 for moving those object to `::Kernel`. (But when?)

When #86 was composed, we didn't have `%a{annotate:rdoc:copy:???}` annotation. But today we have, and we can have the RBS definitions in `Kernel` while it copies the docs form `Object` methods.

The doc says:

> Object クラスのメソッドは実際にはこのモジュールで定義されています。これはトップレベルでのメソッドの再定義に対応するためです。 https://docs.ruby-lang.org/ja/latest/class/Kernel.html

> (I cannot find the english version.) Methods of Object class are actually defined in this module. This is for over-writing methods in top-level. 

So, for this purpose, RBS definition should be in `Kernel` module too. (While it's not very clear to me what it means... Does it mean we can call the originals with `super` ??)

**Comment by ParadoxV5** [comment]
> (I cannot find the english version.)

> Although the instance methods of [`Object`](https://docs.ruby-lang.org/en/master/Object.html) are defined by the [`Kernel`](https://docs.ruby-lang.org/en/master/Kernel.html) module, we have chosen to document them here for clarity.
> ⸺ [`Object`](https://docs.ruby-lang.org/en/master/Object.html)

---

Truthfully, I too prefer everything defined under `Kernel` to document in `Kernel` to represent how things are done. But Team Core had reasons.
In the mean time, I also prefer RBS to match the Ruby docs (whether they decide `Object` or `Kernel`) for consistency.

**Comment by ksss** [comment]
Thank you for the comment. It seems you can call `super` with top-level redefinitions. Interesting.

```rb
p method(:puts)
#=> #<Method: Object(Kernel)#puts(*)>

def puts(*)
  print "before\n"
  super
  print "after\n"
end

puts "hello"
#=> before
#=> hello
#=> after

p method(:puts)
#=> #<Method: Object#puts(*) t.rb:1>

p method(:puts).super_method
#=> #<Method: Kernel#puts(*)>
```

**Comment by ksss** [comment]
I've come across an interesting ticket.

https://bugs.ruby-lang.org/issues/19304

It seems that RDoc is moving away from the hack of treating Kernel methods as Object methods.
I think, it seems that the decision to migrate methods from Object to Kernel was the right one.
