### ISSUE TITLE
Migrate rbs prototype command information from soutaro/steep to ruby/rbs

### ISSUE THREAD

**Issue by Forthoney** [ruby/rbs#1614]
It's unfriendly that this repo does not really have a description of what the different `rbs prototype` options do. Instead users need to go to the [Steep ](https://github.com/soutaro/steep/blob/f68f477d6050cd0d2bd80f38c4645f72b7b04a11/README.md?plain=1#L202) repository. I propose that we move the description (or at least copy it over). This can be done as a larger goal of making a user's manual for the RBS CLI.

**Comment by soutaro** [comment]
It totally makes sense! +1 for copying this.
