### ISSUE TITLE
%a{pure} does not seem to work for attr_reader

### ISSUE THREAD

**Issue by HoneyryderChuck** [ruby/rbs#1872]
I see that the `%a{pure}` label can be added to `def` to indicate the return value of a function is pure (which helps in type narrowing), but the same does not seem to work for attribute readers:

```ruby
# class A
#   %a{pure} attr_reader b: String?
# end

class A
  attr_reader :b
 def initialize(b = nil); @b = b; end
end

a = A.new("bang")

if a.b
  # steep still consider b to be String, not String?

**Comment by ParadoxV5** [comment]
Did you mean?  Steep still consider b to be `String?`, not `String`

Reproduced in Steep 1.7

**Comment by ParadoxV5** [comment]
Aren’t `attr_XXX` be pure by definition?
unless they’re used by lazy people to write RBS for their custom accessors

**Comment by HoneyryderChuck** [comment]
you're correct, it's already pure. I got confused by the message.
