### ISSUE TITLE
CI fails due to RBS::EnvironmentLoader::UnknownLibraryError

### ISSUE THREAD

**Issue by rhiroe** [ruby/rbs#2082]
Recently, CI has been failing due to RBS::EnvironmentLoader::UnknownLibraryError.

3.7.0.dev.0 does not match in `Gem::Dependency.new('rbs').matching_specs`.
The cause seems to be [this commit](https://github.com/rubygems/rubygems/commit/c80998a22ad06e3bf31347cde446d3f64b1f5c65).

When you run `bundle exec irb`, you will get the following message.

```
Ignoring rbs-3.7.0.dev.0 because its extensions are not built. Try: gem pristine rbs --version 3.7.0.dev.0
```

As per this message, the extension must be built to match.

**Comment by soutaro** [comment]
Fixed with https://github.com/ruby/rbs/pull/2084 by skipping the `rbs` signature validation...
