### ISSUE TITLE
How to type subclasses of a parent class?

### ISSUE THREAD

**Issue by KieranP** [ruby/rbs#2104]
How can I type something to allow subclasses of a class?

Slimmed down example case:

Ruby:
```ruby
class Inventory
  attr_accessor :items
end

class Items
  class Base
  end

  class Shield < Base
  end

  class Sword < Base
  end
end
```

Current RBS:
```rbs
class Inventory
  attr_accessor items: Array[::Items::Base]
end

class Items
  class Base
  end

  class Shield < Base
  end

  class Sword < Base
  end
end
```

This doesn't work though, `Array[::Items::Base]` will only allow that specific class.

Is there a way to do this? e.g. `Array[::Items::*]` or `Array[subclasses(::Items::Base)]` ?

To work around this, I currently have to manually specify all subclasses, which is cumbersome and prone to drift.

**Comment by KieranP** [comment]
@ParadoxV5 Sorry, my original example is not clear. Inventory#items array needs to accept any item that is a subclass of Items::Base. e.g. `inventory.items << ::Item::Sword`. At the moment, I'm forced to type inventory items as `Array[::Items::Shield | ::Items::Sword | ::Item::Pickaxe | .......]`. If I have 100 items, I need to specify all 100 classes in the type, cumbersome and ugly.

I'm proposing for a wildcard or `subclasses` declaration, that allows any class that is subclassed from a common class. So instead of the above type declaration where I need to include 100s of items, I should be able to do something like either `Array[subclasses(::Item::*)]` or `Array[subclasses(::Item::Base)]`. Much cleaner, readable, and maintainable.

**Comment by ParadoxV5** [comment]
works on my machine
```console
$ cat ruby.rb rbs.rbs; ruby ruby.rb; steep check
class Inventory
  # soutaro/steep#1036
  def items
    @items ||= []
  end
end

inventory = Inventory.new
inventory.items << 1
inventory.items << 0x2
inventory.items << 3.0
inventory.items << 4r

p inventory.items
class Inventory
  attr_reader items: Array[Numeric]
end
[1, 2, 3.0, (4/1)]
# Type checking files:

.....................................................................................

No type error detected. 🧋
```
What’s the error you’re getting?

**Comment by KieranP** [comment]
Looks like it was just a way I had things setup. I tweaked a couple of things to make the class inheritance a bit more straightforward (closer to the examples above), and it appears to be working now.

Might be good if this functionality were documented better. When I look at the RBS syntax and RBS by example docs, there are now references to "subclass" and only one to "inherit" which is unrelated. There is currently nothing to indicate that the RBS spec defines using parent classes as types also allowing child classes of that type.

**Comment by ParadoxV5** [comment]
> Looks like it was just a way I had things setup. I tweaked a couple of things to make the class inheritance a bit more straightforward (closer to the examples above), and it appears to be working now.

Would you mind sharing what you had originally too? It could be an oversight in the system, and I’m curious in general 🙃.

> Sorry for the confusion and thanks for the help.

No problem; welcome to RBS.

> using parent classes as types also allowing child classes of that type

Polymorphism (:

**Comment by KieranP** [comment]
@ParadoxV5 

> > using parent classes as types also allowing child classes of that type
> 
> Polymorphism (:

I meant that the documentation for RBS, rbs-inline, and steep are all devoid of any reference to "subclass", "inherit" and "polymorphism". If you search all docs and code, there appears to be no reference to those keyboard. So the docs do not clearly indicate that using "BaseClass" as a type also allows any subclasses from it.
