### ISSUE TITLE
Methods that start with an underscore are interpreted by the parser as interfaces

### ISSUE THREAD

**Issue by connorshea** [ruby/rbs#220]
```ruby
class Foo
  def self._bar?(baz)
    return baz
  end
end

puts Foo._bar?('qux') #=> 'qux'
```

I noticed this when running `bundle exec rbs parse bundler.rbs` for a `bundler.rbs` created from sorbet-typed's `bundler.rbi`. Bundler has a method called `_path_to?`, so this definitely happens in actual Ruby code (though it's probably rare).

The RBS file:

```
class Foo
  def self._path_to?: (untyped baz) -> untyped
end
```

`rbs parse foo.rbs` gets me this error:

```
foo.rbs:2:11: parse error on value: (tINTERFACEIDENT)
```

**Comment by pocke** [comment]
This problem has been fixed in https://github.com/ruby/rbs/pull/304 so I'll close this issue.
