### ISSUE TITLE
`rbs prototype runtime` didn't work with a class including anonymous modules

### ISSUE THREAD

**Issue by tadd** [ruby/rbs#301]
With class `C` in `./c.rb`

```ruby
class C
  include Module.new
end
```

this command fails.

```
$ bundle2.7 exec rbs prototype runtime --require ./c C
Traceback (most recent call last):
	13: from /home/tadashi/git/rbs/vendor/bundle/ruby/2.7.0/bin/rbs:23:in `<main>'
	12: from /home/tadashi/git/rbs/vendor/bundle/ruby/2.7.0/bin/rbs:23:in `load'
	11: from /home/tadashi/git/rbs/exe/rbs:7:in `<top (required)>'
	10: from /home/tadashi/git/rbs/lib/rbs/cli.rb:85:in `run'
	 9: from /home/tadashi/git/rbs/lib/rbs/cli.rb:455:in `run_prototype'
	 8: from /home/tadashi/git/rbs/lib/rbs/prototype/runtime.rb:40:in `decls'
	 7: from /home/tadashi/git/rbs/lib/rbs/prototype/runtime.rb:40:in `each'
	 6: from /home/tadashi/git/rbs/lib/rbs/prototype/runtime.rb:43:in `block in decls'
	 5: from /home/tadashi/git/rbs/lib/rbs/prototype/runtime.rb:323:in `generate_class'
	 4: from /home/tadashi/git/rbs/lib/rbs/prototype/runtime.rb:64:in `each_mixin'
	 3: from /home/tadashi/git/rbs/lib/rbs/prototype/runtime.rb:64:in `each'
	 2: from /home/tadashi/git/rbs/lib/rbs/prototype/runtime.rb:66:in `block in each_mixin'
	 1: from /home/tadashi/git/rbs/lib/rbs/prototype/runtime.rb:329:in `block in generate_class'
/home/tadashi/git/rbs/lib/rbs/prototype/runtime.rb:53:in `to_type_name': undefined method `split' for nil:NilClass (NoMethodError)
```

This is triggered by the below line because anonymous modules have a name `nil`
https://github.com/ruby/rbs/blob/2646a386f5d412259fd7df601c9a6ad0a0f2b691/lib/rbs/prototype/runtime.rb#L53

but I don't know what to do, so I submitted this issue.

Side-note: This always happened when I applied `rbs prototype runtime SomeController` to a Rails application controller. Since controllers, at least with Rails 6.0.3.1, seem to always include [an anonymous module](https://github.com/rails/rails/blob/v6.0.3.1/actionpack/lib/action_dispatch/routing/route_set.rb#L481), so the execution fails all the time.

**Comment by soutaro** [comment]
Thanks!

It's not clear how can we fix the issue... So I'd like to propose to implement a workaround for now that:

1. Ignores a mixin if the module doesn't have `#name`, and
2. Print a warning message through `RBS.logger`.

**Comment by pocke** [comment]
Just FYI, I also met the error with an unnamed super class.

```ruby
class C < Class.new
end
```


Real-world example:
https://github.com/rails/rails/blob/df50341fe8e03229308a0389bc14a654bbae666c/activerecord/lib/active_record/attribute_methods/time_zone_conversion.rb#L5-L8
