### ISSUE TITLE
[docs] questions about syntax.md

### ISSUE THREAD

**Issue by sbeckeriv** [ruby/rbs#358]
Dearest Maintainer,

I hope it is an ok day. I was reading over https://github.com/ruby/rbs/blob/master/docs/syntax.md and I was unsure a few things.

1) What format is the syntax documented in? It kind of looks like EBNF but I cant really parse it. 

2) It is meant to be complete? I ask because i see _symbol-literal_ for example but it is not defined on this page.  There are a few of these.

3) Is this a generated page from a script?

Inquiring minds want to know. Thank you for your time.

Becker

**Comment by soutaro** [comment]
Hi @sbeckeriv!

1. I plan to make it something like EBNF, but not sure if there is some formal syntax and it is a valid with respect to the definition.
2. Some non-terminals (for tokens) are missing definitions.
3. No generator but I wrote it manually.

I tried to make terminal symbols with surrounded with backticks and non-terminal symbols with `_`. Other symbols like `::=`, `|`, or `...` are for EBNF.

(I think Markdown is not the best format for this and using HTML or other typesetting tools are better. But, writing .md is easier on GitHub.)

**Comment by sbeckeriv** [comment]
Hello @soutaro 

Thank you for answering my questions. I think this helps me in my parsing. I am unsure if a statement about the current syntax would be helpful for future readers. They can now search EBNF and find this. I dont think there is anything actionable here. 

Thank you again for the information.
Becler
