### ISSUE TITLE
[docs] missing statement clairfications

### ISSUE THREAD

**Issue by sbeckeriv** [ruby/rbs#374]
Dearest Maintainer,

Record type in the syntax doc https://github.com/ruby/rbs/blob/master/docs/syntax.md#record-type where it is part of _type_ 
```
         | `{` _record-name_ `:` _type_ `,` ... `}`     (Record type)
```
uses _record-name_ which is undefined. I add a few questions about what is allowed here.

1) Only symbol version of hashes are allowed to be used and not hashrockets (=>) ?

2) any valid ruby hash symbol is allowed? included but not limited to `{x: 1, X: 1, "y":1}`

3) record-name can not be a class? `{{x:Int}: Int}` as an example?

Second for _literal_ string, symbol and integer are not defined. 

```
_literal_ ::= _string-literal_
            | _symbol-literal_
            | _integer-literal_
            | `true`
            | `false`
```

1 Does integer-literal cover any ruby supported number? Float, Hex(0xa) and a longer list I dont normally use every day? 

I think I have an understand of what can be a symbol and string.

Once again, thank you for your work and time on this project.

Dictated but not reviewed,
Becker

**Comment by soutaro** [comment]
Good point. I don't think the literal syntax are Ruby compatible. Any updates to docs and `parser.y` are welcome!
