### ISSUE TITLE
rbs string literals compatibility with frozen strings

### ISSUE THREAD

**Issue by johansenja** [ruby/rbs#375]
Let's say I have the following class:

```
# foo.rb
class Foo
  BAR = "abc".freeze
end
```
and an equivalent rbs file:
```
# foo.rbs
class Foo
  BAR: "abc"
end
```
If I am using steep and run `bundle exec steep check` I would get the following error: 

```
IncompatibleAssignment: lhs_type="abc", rhs_type=::String (BAR = "abc".freeze)
  ::String <: "abc"
==> ::String <: "abc" does not hold
```

I could, however, do the following with no errors:

```
class Foo
  BAR = "abc"; BAR.freeze
end
```

Is that just because the return type of `String#freeze` is just marked as `::String`?

(rbs version 0.10.0,
steep version 0.24.0,
ruby version 2.7.1)

**Comment by soutaro** [comment]
It's because `"abc".freeze` is not a string literal and it cannot have a literal type. 😫

I agree that `#freeze` calls with literal are so common and will consider implementing a workaround...

**Comment by johansenja** [comment]
Ok fair enough - thanks for the quick update! It would be nice to see it in the future, but I am sure I can manage without for now. Great work on everything so far 👍

**Comment by soutaro** [comment]
This is an issue of Steep. Closing here.
