### ISSUE TITLE
Syntax for class level attributes/class instance variables & class variables

### ISSUE THREAD

**Issue by stevegeek** [ruby/rbs#398]
Hi there, really excited about RBS and am experimenting with `steep`.

Sorry if I have missed it or the reasoning behind this not being supported but wondering if there is a way to express in RBS the following creating a class instance var:

```ruby
class Tester
  class << self
    attr_accessor :var # @var is a String type
  end
end
```

`_attribute-member_` doesn't seem to support a `self.` prefix

Also any syntax for defining the type of class vars (`@@var_name`) ? For example from https://www.ruby-lang.org/en/documentation/faq/8/ 

```ruby
class Woof

  @@sound = "woof"

  def self.sound
    @@sound
  end
end
```

Use of such a construct is mostly discouraged though so maybe RBS is avoiding support for it?

Thanks!

**Comment by soutaro** [comment]
Hi @stevegeek!

I think your proposal makes sense. I'll try to add new syntax like `attr_reader self.var: String`.

`@@sound: String` should work for _class variables_.

Thanks!

**Comment by stevegeek** [comment]
Ah great! Looking forward to it, thanks!

**Comment by palkan** [comment]
Hey @soutaro!

>  I'll try to add new syntax like attr_reader self.var: String.

What about class instance variables not using attr_reader? I mean the following pattern:

```ruby
class A
  class << self
    def foo
      @foo ||= "bar"
    end
  end
end
```

Maybe, it makes sense to add `class << self` support to RBS?

**Comment by palkan** [comment]
^ Nvm, I found that `self.@foo:  String` works (thanks to typeprofiler)

**Comment by soutaro** [comment]
Implemented in https://github.com/ruby/rbs/pull/505.
