### ISSUE TITLE
Runtime type-check breaks with usage of curry

### ISSUE THREAD

**Issue by HoneyryderChuck** [ruby/rbs#445]
I think that the usage of `Proc.curry` is not compatibly with the alias method chain instrumentation way, that is the basis of the current runtime checks.

I have this signature:

```rbs
def on_object: (Object, Object) -> void
```

When I call `on_object(1, 2)`, all good. However, when I do:

```ruby
method(:on_object).curry[1]

#  TypeError: [MyObject#on_object] ArgumentError: expected method type (::Object, ::Object) -> void
```

I've tried updating this locally to come up with a fix, but I don't see any info in the callstack that tells me the method's been called through currying. This might be a ruby limitation, I guess?

**Comment by soutaro** [comment]
I confirmed what is happening with `curry`. The automatically defined method has var-args `*args`, which doesn't work with `curry` without explicitly specifying rarity.

```
method(:on_object).curry(2)[1]   # This works
```

The solution is to define arguments depending on the arity of the original method. Thinking of if it should be done now...

**Comment by HoneyryderChuck** [comment]
Just confirmed that it works. Honestly, your suggestion (passing arity to "curry" call) seems like a decent enough compromise, so I agree that it can be solved another time.

**Comment by HoneyryderChuck** [comment]
@soutaro can you reopen this? These changes seem to have caused syntax errors, at least when curry is used:

```
/usr/local/bundle/ruby/3.0.0/bundler/gems/rbs-b07243f0f5ae/lib/rbs/test/hook.rb:184:in `module_eval': /usr/local/bundle/ruby/3.0.0/bundler/gems/rbs-b07243f0f5ae/lib/rbs/test/hook.rb:81: duplicated argument name (SyntaxError)
...ck, *rest_args_59607f4a, &block)
...                          ^~~~~
        from /usr/local/bundle/ruby/3.0.0/bundler/gems/rbs-b07243f0f5ae/lib/rbs/test/hook.rb:184:in `hook_instance_method'
        from /usr/local/bundle/ruby/3.0.0/bundler/gems/rbs-b07243f0f5ae/lib/rbs/test/tester.rb:64:in `block (2 levels) in install!'
        from /usr/local/bundle/ruby/3.0.0/bundler/gems/rbs-b07243f0f5ae/lib/rbs/test/tester.rb:53:in `each'
        from /usr/local/bundle/ruby/3.0.0/bundler/gems/rbs-b07243f0f5ae/lib/rbs/test/tester.rb:53:in `block in install!'
        from <internal:kernel>:90:in `tap'
        from /usr/local/bundle/ruby/3.0.0/bundler/gems/rbs-b07243f0f5ae/lib/rbs/test/tester.rb:45:in `install!'
        from /usr/local/bundle/ruby/3.0.0/bundler/gems/rbs-b07243f0f5ae/lib/rbs/test/setup.rb:69:in `block in <top (required)>'

**Comment by soutaro** [comment]
@HoneyryderChuck Oh... 🙇‍♂️
