### ISSUE TITLE
Declare a subclass of another class

### ISSUE THREAD

**Issue by HoneyryderChuck** [ruby/rbs#448]
Say that, I have class A, and subclass B:

```ruby
class A
end

class B < A
end

def foo; [A, B].sample; end
```

How can I declare that foo returns a subclass of A? Because `def  foo: () -> singleton(A)` doesn't work.

**Comment by soutaro** [comment]
Seems like we can test the relationship between `singleton(A)` and `singleton(B)` using `Object#singleton_class`.
