### ISSUE TITLE
Runtime requires

### ISSUE THREAD

**Issue by HoneyryderChuck** [ruby/rbs#452]
Currently, runtime checks raises an exception if one of the typed classes isn't loaded yet.

This is not ideal for cases when you want to delay `require`ing a certain class, or if the module is optional.

Is there a workaround already, or is this a bug?

**Comment by soutaro** [comment]
Good point. This is intended behavior but I agree that it's better to allow type checking classes even if it's not loaded yet. Will open a PR. 💪

**Comment by soutaro** [comment]
My understanding is the following code causes the problem:

```rbs
class Foo
  def f: () -> (Bar | Baz)
end

class Bar
end

class Baz
end
```

```rb
class Foo
  def f
    Baz.new
  end
end

class Baz end

Foo.new.f()       # Type checking the return value of `f` causes `value.is_a?(Bar)` but `Bar` is not defined yet.
```

**Comment by HoneyryderChuck** [comment]
It's exactly that! Thx in advance for the effort
