### ISSUE TITLE
It defines wrong `Class#new` type from `initialize`

### ISSUE THREAD

**Issue by pocke** [ruby/rbs#459]
`DefinitionBuilder` defines `Class#new` method if it doesn't exist and `initialize` is available for the instance.

https://github.com/ruby/rbs/blob/8247716d6540cdb7461357945b0260cf38b2c12d/lib/rbs/definition_builder.rb#L902-L951

But it has two problems.

First, it conceals `new` method that is defined in an ancestor.
For example:

```rbs
# RBS

class C
  def self.new: (String) -> untyped
end

class C2 < C
end
```

```console
# it is ok.
$ rbs -I . method --singleton C new
::C.new
  defined_in: ::C
  implementation: ::C
  accessibility: public
  types:
      (::String) -> untyped

# It should be `(::String) -> untyped`, but doesn't.
$ rbs -I . method --singleton C2 new
::C2.new
  defined_in: 
  implementation: 
  accessibility: public
  types:
      () -> ::C2
```

Second, it defines `new` method for Module unexpectedly.
For example:

```rbs
# RBS

module M
  def initialize: (String, Integer) -> void
end
```

```bash
# M.new should not exist, but it exists.
$ rbs -I . method --singleton M new
::M.new
  defined_in: 
  implementation: 
  accessibility: public
  types:
      (::String, ::Integer) -> ::M
```

**Comment by soutaro** [comment]
Changed the milestone since I found this is more difficult than I expected.
