### ISSUE TITLE
rbs prototype rb vs. class << self

### ISSUE THREAD

**Issue by palkan** [ruby/rbs#510]
Example code:

```ruby
# a.rb
class A
  class << self
    attr_reader :foo

    def bar
      "baz"
    end
  end
end
```

Generated signature:

```
$ rbs -v
rbs 0.19.0

$ rbs prototype rb a.rb

class A
  attr_reader foo: untyped

  def self.bar: () -> "baz"
end
```

The signature declares `attr_reader` for the class instances, not the singleton.

(Also, we currently don't support _self_ attr_reader/writer, right? Or am I missing something)

**Comment by soutaro** [comment]
I think the improvements in the latest version `0.20.1` would help. (https://github.com/ruby/rbs/pull/502 and https://github.com/ruby/rbs/pull/505)
