### ISSUE TITLE
Can't create an alias to singleton attribute

### ISSUE THREAD

**Issue by pocke** [ruby/rbs#514]
Singleton attribute accessor has been introduced by #502. I tried to use it in RBS Rails but I got an error with this feature and alias.

```rbs
# ok
class A
  def self.foo: -> untyped
  alias self.bar self.foo
end

# ok
class B
  attr_reader foo: untyped
  alias bar foo
end

# It raises RBS::UnknownMethodAliasError
class C
  attr_reader self.foo: untyped
  alias self.bar self.foo
end
```

RBS raises an `RBS::UnknownMethodAliasError` on an alias to singleton attribute.

In other cases, which are aliases to a singleton method or an instance attribute, they don't raise any error. So I think the singleton attribute case also should work.

**Comment by soutaro** [comment]
Fixed by #516
