### ISSUE TITLE
[Bug] RBS::Parser.parse_signature unable to parse .rbs generated for method with argument forwarding 

### ISSUE THREAD

**Issue by oolkhovoy** [ruby/rbs#554]
```shell
> ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
> rbs -v
rbs 1.0.0
```

Result of `rbs prototype rb` for 
```ruby
class Foo
  def bar(...)
    puts(...)
  end
end
```
is
```rbs
class Foo
  def bar: (*untyped *) { () -> untyped } -> untyped
end
```
Yet `RBS::Parser.parse_signature` unable to parse above rbs and fails with
```shell
parser.y:1419:in `on_error': parse error on value: #<RBS::Parser::LocatedValue:0x00007fee22894820 @location=#<RBS::Location:780 @buffer=, @pos=49...50, source='*', start_line=3, start_column=26>, @value="*"> (kSTAR) (RBS::Parser::SyntaxError)
	from (eval):3:in `_racc_do_parse_c'
	from (eval):3:in `do_parse'
	from parser.y:1124:in `parse_signature'
	from /Users/olegolkhovoy/RubymineProjects/untitled8/fc/cat.rb:5:in `<main>'
```

**Comment by pocke** [comment]
Thanks for your feedback!


It is a bug of `rbs prototype rb`. The generated RBS is invalid.
RubyVM::AbstractSyntaxTree returns `:*` as an argument name when the `def` use the argument forwarding syntax.
But `*` is not allowed as an argument name in RBS, so it causes a syntax error.



I've fixed this problem on #560.
The `*` argument name will be omitted by this change.
