### ISSUE TITLE
[prototype runtime] Generate classes with the nested style

### ISSUE THREAD

**Issue by pocke** [ruby/rbs#562]
Currently `rbs prototype runtime` command generates classes/modules with `::` style. For example, `class Foo::Bar end`.
But I'd like to change it to the nested style, such as `class Foo class Bar end end`.

# Motivation

I like the nested style, and the style has benefits compared to `::` style.

* Easy to access constants in the same namespace
  * ```ruby
    # with `::` style
    class A::B::C
      def foo: () -> A::B::D
    end

    # with nested style
    class A
      class B
        class C
          def foo: () -> D
        end
      end
    end
    ```
* Parent namespaces are always available.
  * `class A::B::C end` is invalid as RBS when `A` or `A::B` is not defined in another place.
  * But the nested style defines all parent namespaces explicitly.
* `rbs prototype rb` generates classes with the nested style.

---

By the way, I found a bug of prototype runtime. Prototype runtime omits namespaces incorrectly.
For example:

```ruby
# test.rb

module A
  module B
    module C
    end

    module D
      include C
    end
  end
end
```

```ruby
$ rbs prototype runtime -R test.rb 'A::*'
module A::B
end

module A::B::C
end

module A::B::D
  include C       # <- C is not available in this context.
end
```

I'll also fix this problem with this issue, because the nested style make it easy to fix.

---

@soutaro Do you have any thoughts about this change? 
I found a pull request that changes prototype rb's behavior https://github.com/ruby/rbs/pull/315, but I couldn't find any mentions for prototype runtime. If there're any concerns, I'd like to know that.

**Comment by soutaro** [comment]
This is just because *nested syntax* is introduced recently. It's a great idea to generate in *nested syntax*. 👍
