### ISSUE TITLE
Type `::Numeric` does not have method `+`

### ISSUE THREAD

**Issue by HoneyryderChuck** [ruby/rbs#609]
I'm getting the following error when using `steep`, for an operation defined like:

```ruby
def add: (Numeric a, Numeric b) -> Numeric
```

This seems to be because [+ is defined as a method in all subclasses of numeric](https://github.com/ruby/rbs/blob/master/core/integer.rbs#L69). However, I'd argue that such a signature is legitimate, don't you agree? Or am I missing smth?

**Comment by soutaro** [comment]
@HoneyryderChuck Good catch! It should make sense to have operations in `Numeric` like:

```rbs
class Numeric
  def +: (Numeric) -> Numeric
end
```
