### ISSUE TITLE
How to define different signatures for each supported ruby versions?

### ISSUE THREAD

**Issue by kachick** [ruby/rbs#613]
https://github.com/ruby/rbs/blob/11d99dbe7de1cd9da6487ad0a153424b6452ee15/docs/CONTRIBUTING.md#the-target-version

The section describes as below

>The Target Version
The standard library signatures targets Ruby 2.7 for now.
The library code targets Ruby 2.6, 2.7, and 3.0.

How about to add/modify signatures for `core/` in each ruby versions?
e.g.) Ruby 3.0 added `Hash#except`, but it looks nothing in `core/hash.rbs`. Does `rbs` have any version guard feature?

**Comment by soutaro** [comment]
The doc is wrong... The target right now is `3.0`.

We don't have a plan to introduce something like version guard yet.

**Comment by kachick** [comment]
I see! So I close this issue. And I might try some PRs around the doc and `hash.rbs` :)
