### ISSUE TITLE
rbs/test/setup fails when defining additional methods in a core class

### ISSUE THREAD

**Issue by jubishop** [ruby/rbs#643]
I've added my own method to the class String.  I can `steep check` it fine, and my `rspec` tests pass it just fine.  I can also set up unique class names and run `rbs/test/setup` with great success, but when I try to run it against a file importing my file that adds definitions to the existing String class, it blows up.  It appears to try to set up method hooks twice, which causes the error, here's what I get:

```
📚jubishop:~/Desktop/core#>RBS_TEST_TARGET='String::*' RUBYOPT='-rrbs/test/setup' bundle exec rspec
I, [2021-03-14T21:24:26.060639 #70358]  INFO -- : Setting up hooks for ::String
I, [2021-03-14T21:24:26.060733 #70358]  INFO -- rbs: Installing runtime type checker in String...
I, [2021-03-14T21:24:26.077752 #70358]  INFO -- rbs: Setting up method hook in #==...
I, [2021-03-14T21:24:26.078465 #70358]  INFO -- rbs: Setting up method hook in #initialize...
I, [2021-03-14T21:24:26.078970 #70358]  INFO -- rbs: Setting up method hook in #initialize_copy...
I, [2021-03-14T21:24:26.079481 #70358]  INFO -- rbs: Setting up method hook in #<=>...
I, [2021-03-14T21:24:26.079893 #70358]  INFO -- rbs: Setting up method hook in #===...
I, [2021-03-14T21:24:26.080299 #70358]  INFO -- rbs: Setting up method hook in #=~...
I, [2021-03-14T21:24:26.080582 #70358]  INFO -- : Setting up hooks for ::String
I, [2021-03-14T21:24:26.080602 #70358]  INFO -- rbs: Installing runtime type checker in String...
I, [2021-03-14T21:24:26.080730 #70358]  INFO -- rbs: Setting up method hook in #=~...

An error occurred while loading ./spec/string_spec.rb.
Failure/Error: end

SyntaxError:
  /Users/jubishop/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.1.1/lib/rbs/test/hook.rb:82: syntax error, unexpected '(', expecting ';' or '\n'
  ...with__RBS_TEST_c69d39_a95e448a(req, *rest_args__a95e448a, &b...
  ...                              ^
  /Users/jubishop/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rbs-1.1.1/lib/rbs/test/hook.rb:82: syntax error, unexpected &
  ...8a(req, *rest_args__a95e448a, &block__a95e448a)
  ```
  
  thanks for any help!

**Comment by soutaro** [comment]
Thank you for reporting the issue.

[The list of operators](https://github.com/ruby/rbs/blob/9a2121f156a9a895748fb11098f94c3579d0402f/lib/rbs/test/hook.rb#L7-L29) is in-complete and it's causing the issue.

**Comment by soutaro** [comment]
I want to mention that running the runtime test on `String` causes an infinite loop, because `String` methods are used in the RBS library itself. So, I don't recommend trying it...

**Comment by jubishop** [comment]
thanks @soutaro .  Is there any way I can runtime test the usage of methods I've added to the String class, then?  in my case, I've added a method named `pluralize`.

**Comment by soutaro** [comment]
I don't think we can now. It may be a good idea to give a option to specify method names to be tested like:

```
$ rbs test --target 'String#pluralize' ...
```

One workaround may be to extract the methods to a module and run test with the module. (I haven't tested...)

**Comment by jubishop** [comment]
yeah being able to open the core classes and modify them is an awesome feature of Ruby :) it would be nice to have that use-case supported.
