### ISSUE TITLE
How are local variable types inferred?

### ISSUE THREAD

**Issue by sxh** [ruby/rbs#656]
In the body of a method I am creating a local variable and initialising to the result of a method that returns ListingPage?. Inside a loop I am setting the same local variable to the value of another method that also returns ListingPage?. I am getting this error:

Cannot assign a value of type `(::ListingPage | nil)` to a variable of type `::ListingPage`

I cannot understand how the local variable type is being inferred, or can be controlled.

Can anyone suggest an approach to understanding the problem or how to work around it?

**Comment by sxh** [comment]
Update: I user

variable = _ = methodThatReturnsListingPage?

to set the initial value and this removed the error, but it feels very hacky.

**Comment by soutaro** [comment]
Hi @sxh,

You can use casting in Steep `page = _ = ...`, but seems like there is a better way in this case.

```rb
# Raise errors if the method cannot return nil here
page = get_page() || raise
page = get_page() or raise

# Add a guard if the method can return nil here

if page = get_page()
  # page has type of ListingPage here
end

page = get_page()
return if page.nil?
```

In fact, this question is about Steep. So, please consider opening an issue in [soutaro/steep](https://github.com/soutaro/steep) to continue the discussion.
