### ISSUE TITLE
What is a full name of the rbs?

### ISSUE THREAD

**Issue by junaruga** [ruby/rbs#670]
Is the rbs an abbreviation of something right? What is the full name of the rbs?
Is the full name "RuBy Structure" (the `README.md` says "RBS is a language to describe the structure of Ruby programs") or "RuBy type Signature" (the `rbs.gemspec` summary says "Type signature for Ruby.") ?

For example I assume a full name of the irb is "Interactive RuBy".

**Comment by junaruga** [comment]
When I wanted to create a document to explain the rbs, I had the question.

**Comment by soutaro** [comment]
I don't think RBS is an acronym of a _full name_. It implies a combination of RuBy and Signature, but it's not the full name.

I guess it's similar to RPM (is not Redhat Package Manager), PHP (is not Personal Homepage Page tools), or OCaml (is not Objective Caml).

**Comment by junaruga** [comment]
All right. Thanks for the answer. I would close this ticket.

As a reference, in case of RPM, I think it was an acronym of "Red hat Package Manager", now  it is an acronym of "RPM Package Manager".

https://en.wikipedia.org/wiki/RPM_Package_Manager
> RPM Package Manager (RPM) (originally Red Hat Package Manager, now a recursive acronym)
