### ISSUE TITLE
Remove extensions from syntax.md

### ISSUE THREAD

**Issue by Pr0p1k** [ruby/rbs#671]
It's a little misleading that extensions are removed from RBS, but still present in the doc. 
docs/syntax.md:
![image](https://user-images.githubusercontent.com/31842542/115837309-19e13e00-a421-11eb-9e98-9bc9c23dddfd.png)

Probably you need to update all the docs to be consistent with the actual state of RBS. Thanks!

**Comment by pocke** [comment]
The misleading declaration has been removed in https://github.com/ruby/rbs/pull/823/commits/5b8d20a214b7c59418196ce2fa23bd4d2f429921, so I'll close this issue. Thanks for reporting.
