### ISSUE TITLE
Interfaces are (unexpectedly) allowed to begin with lowercase characters after the `_`

### ISSUE THREAD

**Issue by hjwylde** [ruby/rbs#677]
See https://github.com/ruby/rbs/blob/master/lib/rbs/parser.y#L1716, an interface identifier is allowed to begin with a lowercase letter, e.g., `_foo`.

The docs on the other-hand say they cannot: https://github.com/ruby/rbs/blob/master/docs/syntax.md#types, _interface-name_ ::= _namespace_ /_[A-Z]\w*/

I would expect the following code to fail `rbs validate`, but it doesn't:
```
interface _foo
end
```

**Comment by soutaro** [comment]
@hjwylde Thanks. It's a bug.
