### ISSUE TITLE
RBS allows recursive type aliases

### ISSUE THREAD

**Issue by stoyanovskiy239** [ruby/rbs#687]
#### Steps to reproduce
In the terminal:
```
echo "type x = x" >> test.rbs
rbs -I . validate
```

#### Expected
An exception of sorts, with some reasonable error message.

#### Actual
```
Validating alias: `::x`...
```
is present in the output, `validate` execution seems to finish successfully.

#### Environment
```
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
rbs 1.2.1
macOS Catalina 10.15.7
```

**Comment by soutaro** [comment]
Hi @stoyanovskiy239,

Thank you for reporting this issue. Yes. This is clearly a bug. We will implement validation for recursive definitions...
