### ISSUE TITLE
RuntimeError because interface_cache not thread_safe

### ISSUE THREAD

**Issue by HoneyryderChuck** [ruby/rbs#695]
I'm having a non-deterministic error popping up sometimes in CI, around [this part of the rbs code](https://github.com/ruby/rbs/blob/master/lib/rbs/definition_builder.rb#L786-L793), when running "parallel mode" `minitest`. 

I believe that two threads are contending on that code block, where one sets `cc` to `false` then yielding, whereas another thread enters this part before the yield from the previous thread finishes.

I believe that extending `interface_cache` with `Mutex_m` and wrapping that block with `synchronize{}` could mitigate this issue.

**Comment by soutaro** [comment]
Hi @HoneyryderChuck,

Yes, it is not thread safe. My opinion is the builders cannot be shared between threads. Allocating multiple builder objects for each thread or inserting synchronization outside the library should work.

I believe the design makes sense, but let me know if need the classes theirselves to be thread safe.

**Comment by HoneyryderChuck** [comment]
How can I force-initialize the build step then? I understand that it might make the design easier, however I can't control it at the moment, as the parallel runner seems to interfere with this process.

**Comment by soutaro** [comment]
Assuming your problem is testing, I think you can consider using [parallel_tests](https://github.com/grosser/parallel_tests), [test-queue](https://github.com/tmm1/test-queue), or Rake::MultiTask.

**Comment by HoneyryderChuck** [comment]
I don't think that's an option, as I'd be rewriting the test setup with a different framework just because `rbs` doesn't deal with threads.

The way I see it, using the interface is a thread-safe operation (once it's built), as the signatures don't change in between. So why couldn't one explore the possibility of building the environment in a "safe" manner before using it? Or is the interface cache lazy loaded?

**Comment by soutaro** [comment]
My opinion is still _do not share non-immutable objects_. My thoughts:

1. Making the `DefinitionBuilder` thread-safe would be possible, but there are a lot of other classes caching some results.
2. I think most Ruby libraries are not thread safe.
3. I don't think accessing from multi threads in real application rarely makes sense for RBS.

**Comment by soutaro** [comment]
Hi @HoneyryderChuck,

I still don't get what is the problem.

How about using [thread local variable](https://docs.ruby-lang.org/en/3.0.0/Thread.html#method-i-thread_variable_get) in your test? or could you show me code to reproduce the problem.
