### ISSUE TITLE
Kernel.String wrong sig

### ISSUE THREAD

**Issue by HoneyryderChuck** [ruby/rbs#735]
I got an error from Steep while passing a variable typed as `string` to `String(v)` method. Although the error from Steep is probably related to [the problem I tried addressing here](https://github.com/soutaro/steep/pull/396), I think the signature is still wrong, as `Kernel.String` should receive objects implementing `to_str` (`_ToStr` in rbs).

**Comment by soutaro** [comment]
Yes, the type of the `String` method is wrong.
