### ISSUE TITLE
Add support for quoting global variable names

### ISSUE THREAD

**Issue by hjwylde** [ruby/rbs#739]
Global variables in Ruby can have all sorts of characters in their names - https://docs.ruby-lang.org/en/3.0.0/doc/globals_rdoc.html

It would be helpful if we could quote a global variable's name so that we can specify its type.

**Comment by soutaro** [comment]
https://github.com/ruby/rbs/pull/749 You may find improvement here, while it's not completely compatible yet.

**Comment by hjwylde** [comment]
Thank you, looks great :). This can probably be closed now.
