### ISSUE TITLE
Disallow duplicate argument names

### ISSUE THREAD

**Issue by pocke** [ruby/rbs#742]
Currently RBS allows duplicate argument names.

```rbs
# In RBS, all of the following are valid

class C
  def required_positional: (String x, String x) -> void
  def required_keyword:    (x: String, x: String) -> void
  def positional_keyword:  (String x, x: String) -> void
end
```

It conceals mistakes, like https://github.com/ruby/gem_rbs_collection/pull/50.

I'm 100% sure that RBS should reject duplicate keyword argument names. Kwargs are represented as a Hash, which uses argument names as hash keys, so duplicated kwarg names are completely meaningless.
But RBS can distinguish duplicate names in other cases, and it will introduce language change if we fix the problem. So I'm not 100% sure, but it will be useful if RBS reject duplicate argument names for all cases.

**Comment by ksss** [comment]
I agree with you.
In CRuby, it results in a SyntaxError. It seems appropriate for RBS to exhibit the same behavior.

```console
$ ruby -v
ruby 3.3.2 (2024-05-30 revision e5a195edf6) [arm64-darwin22]

## required_positional
$ ruby -we 'def foo(a, a) = 1'
-e:1: duplicated argument name
def foo(a, a) = 1
-e: compile error (SyntaxError)

## required_keyword
$ ruby -we 'def foo(a:, a:) = 1'
-e:1: duplicated argument name
def foo(a:, a:) = 1
-e: compile error (SyntaxError)

## positional_keyword
$ ruby -we 'def foo(a, a:) = 1'
-e:1: duplicated argument name
def foo(a, a:) = 1
-e: compile error (SyntaxError)
```

It seems that Hash report a warning when keys are duplicated.
How should this be handled for record types in RBS?

```
## hash
$ ruby -we 'p({a: 1, a: 2})'
-e:1: warning: key :a is duplicated and overwritten on line 1
{:a=>2}
```

**Comment by ParadoxV5** [comment]
> It seems that Hash report a warning when keys are duplicated. How should this be handled for record types in RBS?
> 
> ```
> ## hash
> $ ruby -we 'p({a: 1, a: 2})'
> -e:1: warning: key :a is duplicated and overwritten on line 1
> {:a=>2}
> ```

I was about to suggest Syntax Error, but then I remembered #1639.
Regarding splatted keys, a warning may be more suitable. We should also consider Ruby’s debate on https://bugs.ruby-lang.org/issues/20331.
```ruby
a = {key: value}
b = {key: a, **a} #=> {key: value}, no warning
```

**Comment by ksss** [comment]
I implemented duplicate argument checking and found duplicates in the following methods in the rbs repository.
However, the names of positional arguments in RBS are like annotations. This might not need to be considered.

- `IO#initialize`
- `IO.popen`
- `IO.open`
- `Time.at`
- `Socket.getaddrinfo`
- `Socket::AncillaryData#initialize`

**Comment by ksss** [comment]
@pocke 
I implementad https://github.com/ruby/rbs/pull/1883
Did you solve your problem?
