### ISSUE TITLE
Resolve logic for superclass/self-types differs from Ruby

### ISSUE THREAD

**Issue by hjwylde** [ruby/rbs#764]
I just want to check whether this is intentional or not, as it could lead to confusion for users or issues when generating RBS code from Ruby code.

```
module A
  class C
  end

  class B < C
    class C
    end
  end
end
```

In Ruby, `B` will inherit from `A::C`. The same code in RBS has a different behaviour; in RBS `B` will inherit from `A::B::C`. This applies to superclass clauses and self-types only from what I can tell.

```
irb(main):010:0> A::B.ancestors
=> [A::B, A::C, Object, Kernel, BasicObject]
```

```
> rbs -Isig ancestors A::B
::A::B
::A::B::C
::Object
::Kernel
::BasicObject
```

**Comment by soutaro** [comment]
Good find! ... 💦 
We should fix the library to make it compatible with Ruby.

**Comment by hjwylde** [comment]
Thank you!
