### ISSUE TITLE
Type variable variance checks for proc types seem to be missing

### ISSUE THREAD

**Issue by hjwylde** [ruby/rbs#831]
Hi! I've been implementing the type variable usage variance checks (the ones which warn when using a covariant/contravariant type variable as incompatible variance) for RubyMine and came across a case that I think is missing in RBS (for `rbs validate`).

```
class Foo[A, in B, out C]
  # Here there are no errors on any of the type variables in the proc type
  def call: -> ^(A | B | C) -> (A | B | C)
end
```

Basically it looks like no type variable usage inside a proc type is checked at all. I would expect there still to be some validation that the type variables are used correctly. In the above example I think I'd expect an error on the first `C` (used as a proc parameter), and the second `B` (used as a proc return type). Similar to how I get an error when I write it out as:

```
class Foo[A, in B, out C]
  def call: -> _Proc[A | B | C, A | B | C]
end

interface _Proc[in Param, out Ret]
  def call: (Param) -> Ret
end
```

Let me know if this sounds right or if I've messed up the logic here.

**Comment by soutaro** [comment]
Thank you for reporting the problem.
Yes, we should have implemented the validation for proc types too.

**Comment by soutaro** [comment]
I was confusing that I remember I have implemented the validation, but I cannot find it. So, it is implemented in https://github.com/ruby/rbs/pull/823/files#diff-8f067645c015ac30d5f0d9d1d65ff40c18529186e5415289198025d84c91eee3, which is not merged yet.

I plan to merge it and ship it as 1.8.0 after releasing 1.7.2 with a fix of #832.

**Comment by hjwylde** [comment]
Perfect, thanks for the update :).

**Comment by soutaro** [comment]
[1.8.0](https://rubygems.org/gems/rbs/versions/1.8.0) is out with the validation implementation. Closing this issue.

**Comment by hjwylde** [comment]
Hey @soutaro, our QA was checking the feature on our side and noticed that there wasn't any errors for the following case:
```
#.rbs
class Foo[A, in B, out C]
  def foo: ( ^() {(C) -> B} -> void) -> void
end
```

After looking at the patch I think checking variances inside the blocks of procs is missing, is that right, or was it intentional?
