### ISSUE TITLE
No errors for the use of type variables in singleton methods

### ISSUE THREAD

**Issue by hjwylde** [ruby/rbs#832]
Take the following examples:
```
class Foo[A]
  @@foo1: A
  def self.foo2: -> A
  def self?.foo3: -> A
  attr_accessor self.foo4: A
  attr_reader self.foo5: A
  attr_writer self.foo6: A
end
```

RBS currently has an error on `@@foo1`, as it cannot find `A`. This is correct as we're in a singleton context and `A` cannot refer to the class type variable. Currently though there are no errors on `foo2` through to `foo6`. I would expect there to be an error on all of these cases as they are all singleton contexts. N.B., the methods can still have method type variables, just not class ones.

**Comment by soutaro** [comment]
This should be a bug. 🙇‍♂️

**Comment by soutaro** [comment]
Could you tell me which version did you test?

It seems like the latest version, 1.7, correctly parses the cases. https://github.com/ruby/rbs/pull/833 (I guess versions before 1.7 didn't.)

**Comment by hjwylde** [comment]
Looks like you're right, I was on 1.6.1 but now on 1.7.1 there are errors as expected. I'll close the issue, thanks :).
