### ISSUE TITLE
rbs parse raises error on ~@

### ISSUE THREAD

**Issue by sevenc-nanashi** [ruby/rbs#837]
![image](https://user-images.githubusercontent.com/59691627/144923128-fd0edd71-6ed4-40c9-8f5e-98bf3997f691.png)
Ruby supports `~@`, but `rbs parse` says it's error.
![image](https://user-images.githubusercontent.com/59691627/144923803-f3176f58-520e-495d-a742-127ceab018e0.png)

## enviroments
Ruby 3.0.2
rbs 1.8.0

**Comment by ksss** [comment]
@sevenc-nanashi Hi.
 
How about like this rbs?

```rb
class Obj
  def ~: () -> String
end
```

`~o` will call `#~` method.

```
$ ruby -e '~Object.new'
-e:1:in `<main>': undefined method `~' for #<Object:0x000000015118bcd8> (NoMethodError)
```

The reason why `def ~@; end` can be defined in ruby is probably related to this problem.
https://bugs.ruby-lang.org/issues/10463

**Comment by sevenc-nanashi** [comment]
Thanks, I didn't know this is ruby bug. I solved problem with `def ~:`. idk I should close this issue, so please close it if it's not needed.
