### ISSUE TITLE
Add error when using type variables in an `extend` statement

### ISSUE THREAD

**Issue by hjwylde** [ruby/rbs#838]
We came across a case with `rbs validate` recently that we think should have an error:
```
class Foo[A]
  extend Bar[A]
end

module Bar[A]
end
```

We think that `Bar[A]` should have an error because extend is adding the methods to the singleton class, so it won't have access to instance type variables. This is similar to the other cases of singleton methods, class variables, etc.

**Comment by soutaro** [comment]
@hjwylde RBS 1.8.1 is out with an update for this.

**Comment by hjwylde** [comment]
Thanks @soutaro for the fast addition!
