### ISSUE TITLE
Move stdlib/rubygems/ to core/rubygems/

### ISSUE THREAD

**Issue by pocke** [ruby/rbs#872]
I propose to move RubyGems library's RBS from stdlib to core.

In Ruby, `rubygems` is loaded by default unless `--disable-gems` is given.
`--disable-gems` option is provided only for debugging Ruby core. So we can suppose `rubygems` is loaded always.

But currently RBS provides `rubygems` as a standard library, so the user needs to load `rubygems` explicitly in RBS. It is different from Ruby.

So I think RBS should provide `rubygems` as a core library. 

# Cons

* Performance
  * Loading RBSs will be slower by this change to parse/load `rubygems.rbs`.
  * I guess the parsing cost is small so we can ignore it.
* Compatibility
  * If `rubygems` library is used in existing code, it will causes a load error (or something) by this change.
  * For example, `library 'rubygems'` in `Steepfile` will raise an error if `rubygems` library is gone.

**Comment by soutaro** [comment]
Sounds good! 👍
