### ISSUE TITLE
Suggestion for "Standard library", "stdlib" wording

### ISSUE THREAD

**Issue by snaka** [ruby/rbs#876]
In the current RBS documentation, the terms `Standard library` and `stdlib` seem to refer to different things in different places.
This seems to confuse people like me who are reading the RBS documentation for the first time.

For example
The document title [Standard Library Signatures Contribution Guide](https://github.com/ruby/rbs/blob/master/docs/CONTRIBUTING.md#standard-library-signatures-contribution-guide) implicitly says that core classes (built-in classes) are out of scope for this document.
However, the content seems to cover core classes as well (am I wrong?).
This is why it is confusing.

According to the notation in https://ruby-doc.org/, it seems more appropriate to use the following for each of them.

- **Core class (abbreviation: `core`)**
  - A class built into the Ruby language (Array, Hash, etc.).
  - See also: https://ruby-doc.org/core-3.0.3/
- **Standard library (abbreviation: `stdlib`)**
  - Libraries bundled with Ruby (Base64, CSV, etc.)
  - See also: https://ruby-doc.org/stdlib-3.1.0/

For the above reasons, I think it would be better to match the current wording in documents and directories with that in ruby-doc.org.
 (If you need help with this, please let me know).

**Comment by soutaro** [comment]
Thank you for filing this issue.

I agree that using _core_ and _stdlib_ is a good idea, and I updated some of the docs in [this PR](https://github.com/ruby/rbs/pull/883).

Any feedback is welcome. 🙏

**Comment by snaka** [comment]
I believe that most of the major points that could cause misunderstandings in the PR #883 have been fixed.

Thank you for taking time in your busy day to respond! 👍
