### ISSUE TITLE
CI failed by unsafe repository

### ISSUE THREAD

**Issue by buzztaiki** [ruby/rbs#983]
e.g. https://github.com/ruby/rbs/runs/6148027791?check_suite_focus=true#step:9:7

According to the following, `set-safe-directory` has been added to the `checkout` action to address this issue.
- https://github.com/actions/checkout/issues/760
- https://github.com/actions/checkout/pull/770

**Comment by jtyr** [comment]
I'm having the same problem. All  my builds are failing now and were absolutely fine before the mentioned change. I don't want to add the workaround (`git config --global --add safe.directory "$PWD"`) to all workflows in all my repos. Please fix it.
